### ISSUE TITLE
[bug]: webpack fails to build in production 

### ISSUE THREAD

**Issue by ali-garajian** [JaylanChen/node-express-hbs-webpack-demo#2]
Hi there! 
[According to this](https://github.com/js-dxtools/webpack-validator/issues/155) `OccurrenceOrderPlugin` is now enabled by default, and there's no need to include it as a plugin anymore; 
So, you can just change this line
`plugins: [new CleanWebpackPlugin(), new webpack.optimize.OccurrenceOrderPlugin()]`
to this
`plugins: [new CleanWebpackPlugin()]`
in `webpack.production.js`, and the error goes away.

BTW, thanks for this setup. I'm fairly new to node, and this repo answered a lot of questions for me :)

**Comment by JaylanChen** [comment]
Sorry, I may not have noticed the notice of GitHub, so I didn't see this issue until now .

Thanks for your reminding, I will fix this bug immediately.
